//Add some extra wrapping around the library autogenerated from the swagger.  

var apiClient = require('./src/index.js');

var api = new apiClient.TilesApi();

//All following requests will have the header:
//apiKey: the_key 
api.setApiKeyHeader = (apiKey) => {
	api.apiClient.authentications.apiKeyHeader.apiKey = apiKey;
}

//All following requests will have the query string:
//?apiKey=the_key
api.setApiKeyQuery = (apiKey) => {
	api.apiClient.authentications.apiKeyQuery.apiKey = apiKey;
}

//Returns the URL to pass to map libraries like leaflet.
api.getPNGTileURL = (ownerId, layerId, instanceId, time, level) => {

	//The dataset might not have levels.
	if(!level) {
		level = 0;
	}

	var urlTemplate = `/${ownerId}/tile/${layerId}/${instanceId}/${time}/${level}/{z}/{x}/{y}.png`
	var tileURL = api.apiClient.basePath + urlTemplate;

	//Add the apiKey to the url if it is set.
	if(api.apiClient.authentications.apiKeyQuery.apiKey) {
		tileURL += "?apiKey=" + api.apiClient.authentications.apiKeyQuery.apiKey;
	}

	return tileURL;
}

module.exports = api;