/**
 * WXTiles
 * Make and explore beautiful, rapidly-refreshed weather maps with the WXTiles API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Levels', 'model/PartialInstance', 'model/Times'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Levels'), require('./PartialInstance'), require('./Times'));
  } else {
    // Browser globals (root is window)
    if (!root.WxTiles) {
      root.WxTiles = {};
    }
    root.WxTiles.Instance = factory(root.WxTiles.ApiClient, root.WxTiles.Levels, root.WxTiles.PartialInstance, root.WxTiles.Times);
  }
}(this, function(ApiClient, Levels, PartialInstance, Times) {
  'use strict';




  /**
   * The Instance model module.
   * @module model/Instance
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>Instance</code>.
   * A named instance of a dataset, typically used to represent a forecast model cycle. Includes information on available times and vertical levels (if any).
   * @alias module:model/Instance
   * @class
   * @param instance {module:model/PartialInstance} 
   * @param times {module:model/Times} 
   * @param levels {module:model/Levels} 
   */
  var exports = function(instance, times, levels) {
    var _this = this;

    _this['instance'] = instance;
    _this['times'] = times;
    _this['levels'] = levels;
  };

  /**
   * Constructs a <code>Instance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Instance} obj Optional instance to populate.
   * @return {module:model/Instance} The populated <code>Instance</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('instance')) {
        obj['instance'] = PartialInstance.constructFromObject(data['instance']);
      }
      if (data.hasOwnProperty('times')) {
        obj['times'] = Times.constructFromObject(data['times']);
      }
      if (data.hasOwnProperty('levels')) {
        obj['levels'] = Levels.constructFromObject(data['levels']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PartialInstance} instance
   */
  exports.prototype['instance'] = undefined;
  /**
   * @member {module:model/Times} times
   */
  exports.prototype['times'] = undefined;
  /**
   * @member {module:model/Levels} levels
   */
  exports.prototype['levels'] = undefined;



  return exports;
}));


