/**
 * WXTiles
 * Make and explore beautiful, rapidly-refreshed weather maps with the Cloudburst API
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LegendItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LegendItem'));
  } else {
    // Browser globals (root is window)
    if (!root.WxTiles) {
      root.WxTiles = {};
    }
    root.WxTiles.LegendPlot = factory(root.WxTiles.ApiClient, root.WxTiles.LegendItem);
  }
}(this, function(ApiClient, LegendItem) {
  'use strict';




  /**
   * The LegendPlot model module.
   * @module model/LegendPlot
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>LegendPlot</code>.
   * A Matplotlib plot type (e.g. &#39;pcolormesh&#39;, &#39;contourf&#39;) as key, with the value representing the information for the legend for that particular sub-plot.
   * @alias module:model/LegendPlot
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>LegendPlot</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LegendPlot} obj Optional instance to populate.
   * @return {module:model/LegendPlot} The populated <code>LegendPlot</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('plotType')) {
        obj['plotType'] = LegendItem.constructFromObject(data['plotType']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/LegendItem} plotType
   */
  exports.prototype['plotType'] = undefined;



  return exports;
}));


