//Add some extra wrapping around the library autogenerated from the swagger.  

var apiClient = require('./index.js');

var api = new apiClient.TilesApi();

//All following requests will have the header:
//apiKey: the_key 
api.setApiKeyHeader = (apiKey) => {
	api.apiClient.authentications.apiKeyHeader.apiKey = apiKey;
}

//All following requests will have the query string:
//?apiKey=the_key
api.setApiKeyQuery = (apiKey) => {
	api.apiClient.authentications.apiKeyQuery.apiKey = apiKey;
}

//Returns the URL to pass to map libraries like leaflet.
//Will include the apiKey query string, if set.
api.getPNGTileURL = (ownerId, layerId, instanceId, time, level) => {

	//The dataset might not have levels.
	if(!level) {
		level = 0;
	}

	var urlTemplate = `/${ownerId}/tile/${layerId}/${instanceId}/${time}/${level}/{z}/{x}/{y}.png`
	var tileURL = api.apiClient.basePath + urlTemplate;

	//Add the apiKey to the url if it is set.
	if(api.apiClient.authentications.apiKeyQuery.apiKey) {
		tileURL += "?apiKey=" + api.apiClient.authentications.apiKeyQuery.apiKey;
	}

	return tileURL;
}

//Helper function for Google Maps.
//Call this with your url and plug the returned object into google maps.
//E.G:
//var layerTilesUrl = wxTiles.getPNGTileURL("wxtiles", "aLayer", "anInstance", "aTime", 0);
//var mapLayer = wxTiles.google.getImageMapType(layerTilesUrl);
//googleMap.overlayMapTypes.setAt(layerKey, mapLayer);
api.googleMaps = {}
api.googleMaps.getImageMapType = (layerTilesUrl) => {
  return new google.maps.ImageMapType({
    getTileUrl: (coord, zoom) => {
      return layerTilesUrl.replace('{z}', zoom).replace('{x}', coord.x).replace('{y}', (Math.pow(2, zoom) - coord.y - 1));
    },
    tileSize: new google.maps.Size(256, 256),
    isPng: true
  })
}

module.exports = api;